#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <uxhw.h>



// Function to calculate lift
double calculate_lift(double v2, double v1, double rho, double A)
{
    double pressure_difference = 0.5 * rho * (pow(v2,2) - pow(v1,2));
    double lift = pressure_difference * airfoil_area;
    return lift;
}

int main(int argc, char *  argv[])
{
	
	const double air_density = 1.225; /* kg/m^3, standard air density at sea level */
	const double air_density_error = 0.085; /* 8.5% error range*/
    double velocity_above, variance_v2;
	double velocity_below, variance_v1;
	double airfoil_area, tolerance_for_area;
	int            c;

	while ((c = getopt(argc, argv, "v:s:u:r:A:t:")) != -1)
	{
		switch (c)
		{
		case 'v':
			
			velocity_above = atof(optarg);
			break;

		case 's':
			
			variance_v2 = atof(optarg);
			break;

		case 'u':
			
			velocity_below = atof(optarg);
			break;

		case 'r':
			
			variance_v1 = atof(optarg);
			break;

		case 'A':
			
			airfoil_area = atof(optarg);
			break;

		case 't':
			
			tolerance_for_area = atof(optarg);
			break;

		default:
			fprintf(stderr, "arguments malformed\n");
			exit(EXIT_FAILURE);
		}
	}

	/*
	 *	Use default if commandline arg not given
	 */
	if (velocity_above == NULL)
	{
		velocity_above = 10.0; /* m/s */
	}
	if (variance_v2 == NULL)
	{
		variance_v2 = 0.5; /* m/s */
	}
	if (velocity_below == NULL)
	{
		velocity_below = 6.0; /* m/s */
	}
	if (variance_v1 == NULL)
	{
		variance_v1 = 0.3; /* m/s */
	}
	if (airfoil_area == NULL)
	{
		airfoil_area = 15.0; /* m^2 */
	}
	if (tolerance_for_area == NULL)
	{
		tolerance_for_area = 0.01; /* m^2 */
	}

	// Assign distributions for uncertainty
	double rho	= UxHwDoubleUniformDist(air_density*(1-air_density_error) , air_density*(1+air_density_error));
	double v2	= UxHwDoubleGaussDist(velocity_above , sqrt(variance_v2));
	double v1	= UxHwDoubleGaussDist(velocity_below , sqrt(variance_v1));
	double A	= UxHwDoubleUniformDist(airfoil_area - tolerance_for_area, airfoil_area + tolerance_for_area);

	// Print parameters
	printf("Velocity above airfoil: %.2f m/s \n", v2);
	printf("Velocity below airfoil: %.2f m/s \n", v1);
	printf("Air density: %.2f kg/m^3 \n", rho);
	printf("Area of airfoil: %.2f m^2 \n", A);

    // Calculate lift
    double lift = calculate_lift(v2, v1, rho, A);

    // Print results
    printf("Lift generated by the airfoil: %.2f N\n", lift);

    return 0;
}
